title: Dr. Obsa Gilo Wakuma
description: Assistant Professor | Computer Science & Engineering | Wollega University
theme: jekyll-theme-minimal

# GitHub Pages settings
url: https://Obsinaan.github.io/Obsa-Gilo-wakuma-PhD-Profile
baseurl: /Obsa-Gilo-wakuma-PhD-Profile

# Basic settings
showDownloadOnGitHub: false

# Social media
github_username: Obsinaan
linkedin_profile: obsa-gilo-ph-d-668b23164
google_scholar: 5638qy4AAAAJ